-- This file is generated by a Matlab script.
-- (C) Michael Wurm 2021
-- *** DO NOT MODIFY ***

library work;
use work.fm_pkg.all;

package filter_bp_pilot_pkg is

constant filter_bp_pilot_coeffs_c : filter_coeffs_t := (
    0.007446289062500,
    0.000793457031250,
    -0.006866455078125,
    -0.012207031250000,
    -0.007110595703125);

end package filter_bp_pilot_pkg;

package body filter_bp_pilot_pkg is
end package body filter_bp_pilot_pkg;
