// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// API
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of config_led_ctrl
//        bit 7~0 - config_led_ctrl[7:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of config_enable_fm_radio_ip
//        bit 7~0 - config_enable_fm_radio_ip[7:0] (Read/Write)
//        others  - reserved
// 0x1c : reserved
// 0x20 : Data signal of status_git_hash_V
//        bit 27~0 - status_git_hash_V[27:0] (Read)
//        others   - reserved
// 0x24 : reserved
// 0x28 : Data signal of status_build_time_V
//        bit 31~0 - status_build_time_V[31:0] (Read)
// 0x2c : Data signal of status_build_time_V
//        bit 15~0 - status_build_time_V[47:32] (Read)
//        others   - reserved
// 0x30 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XFM_RECEIVER_HLS_API_ADDR_CONFIG_LED_CTRL_DATA           0x10
#define XFM_RECEIVER_HLS_API_BITS_CONFIG_LED_CTRL_DATA           8
#define XFM_RECEIVER_HLS_API_ADDR_CONFIG_ENABLE_FM_RADIO_IP_DATA 0x18
#define XFM_RECEIVER_HLS_API_BITS_CONFIG_ENABLE_FM_RADIO_IP_DATA 8
#define XFM_RECEIVER_HLS_API_ADDR_STATUS_GIT_HASH_V_DATA         0x20
#define XFM_RECEIVER_HLS_API_BITS_STATUS_GIT_HASH_V_DATA         28
#define XFM_RECEIVER_HLS_API_ADDR_STATUS_BUILD_TIME_V_DATA       0x28
#define XFM_RECEIVER_HLS_API_BITS_STATUS_BUILD_TIME_V_DATA       48

