%-------------------------------------------------------------------------
% File        : writeConstantsToPythonFile.m
% Author      : Michael Wurm <wurm.michael95@gmail.com>
% Description : Writes filter coefficients to Python file.
%-------------------------------------------------------------------------

function status = writeConstantsToPythonFile( ...
    filename, fp_config, fs, fs_rx, osr_rx)
%writeConstantsToPythonFile - Writes constants to Python file.
%   filename             ... filename (obviously)
%   data                 ... data to be written
%   fp_config.width      ... fixed point width
%   fp_config.width_frac ... fixed point width of fractional part

fileID = fopen(filename, 'w');
if fileID <= 0
    error("Could not open file '%s'!", filename);
end

%% Write Python header

fprintf(fileID, [ ...
    '# This file is generated by a Matlab script.' newline ...
    '# (C) Michael Wurm 2021' newline ...
    '# *** DO NOT MODIFY ***\n\n' ...
    ]);

%% Write constants

fprintf(fileID, "# Global constants for FM Receiver IP and testbench\n");

fprintf(fileID, "fp_width_c      = %d\n", fp_config.width);
fprintf(fileID, "fp_width_frac_c = %d\n", fp_config.width_frac);
fprintf(fileID, "fs_c            = %d\n", fs);
fprintf(fileID, "fs_rx_c         = %d\n", fs_rx);
fprintf(fileID, "osr_rx_c        = %d\n", osr_rx);


fclose(fileID);


status = true;
end
