# This file is generated by a Matlab script.
# (C) Michael Wurm 2021
# *** DO NOT MODIFY ***

fp_width_c      = 16
fp_width_frac_c = 14
fs_c            = 960000
fs_rx_c         = 120000
osr_rx_c        = 8
