# This file is generated by a Matlab script.
# (C) Michael Wurm 2021
# *** DO NOT MODIFY ***

# Global constants for FM Receiver IP and testbench
# Package 'fm_global_spec'

# General
fp_width_c      = 16
fp_width_frac_c = 14

fs_c            = 960000
fs_rx_c         = 120000
fs_audio_c      = 40000

osr_rx_c        = 8
osr_audio_c     = 3

# IP specific
pilot_output_scale_c = 8
carrier_38k_offset_c = 0.75
