-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fm_receiver_filtehbi_rom is 
    generic(
             DWIDTH     : integer := 17; 
             AWIDTH     : integer := 7; 
             MEM_SIZE    : integer := 73
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of fm_receiver_filtehbi_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "00000000000100100", 1 => "11111111110111000", 
    2 => "00000000000000000", 3 => "00000000010001010", 
    4 => "00000000000000100", 5 => "00000000000111100", 
    6 => "11111111100110100", 7 => "00000000000101100", 
    8 => "11111111110111110", 9 => "00000000100001010", 
    10 => "11111111111100010", 11 => "11111111111011010", 
    12 => "11111111100010110", 13 => "11111111110100000", 
    14 => "00000000100100000", 15 => "00000000001011010", 
    16 => "00000000100100000", 17 => "11111110110010000", 
    18 => "00000000000110100", 19 => "11111111001110100", 
    20 => "00000001101100110", 21 => "00000000000000000", 
    22 => "00000000010111010", 23 => "11111110010101110", 
    24 => "11111111001011010", 25 to 26=> "00000000111110100", 
    27 => "00000010011001100", 28 => "11111100101100000", 
    29 => "11111111111001100", 30 => "11111011101001100", 
    31 => "00000110100100100", 32 => "00000000011010000", 
    33 => "00000101111101110", 34 => "11110010101100110", 
    35 => "11110011001011110", 36 => "00100100000100100", 
    37 => "11110011001011110", 38 => "11110010101100110", 
    39 => "00000101111101110", 40 => "00000000011010000", 
    41 => "00000110100100100", 42 => "11111011101001100", 
    43 => "11111111111001100", 44 => "11111100101100000", 
    45 => "00000010011001100", 46 to 47=> "00000000111110100", 
    48 => "11111111001011010", 49 => "11111110010101110", 
    50 => "00000000010111010", 51 => "00000000000000000", 
    52 => "00000001101100110", 53 => "11111111001110100", 
    54 => "00000000000110100", 55 => "11111110110010000", 
    56 => "00000000100100000", 57 => "00000000001011010", 
    58 => "00000000100100000", 59 => "11111111110100000", 
    60 => "11111111100010110", 61 => "11111111111011010", 
    62 => "11111111111100010", 63 => "00000000100001010", 
    64 => "11111111110111110", 65 => "00000000000101100", 
    66 => "11111111100110100", 67 => "00000000000111100", 
    68 => "00000000000000100", 69 => "00000000010001010", 
    70 => "00000000000000000", 71 => "11111111110111000", 
    72 => "00000000000100100" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "block_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "block";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity fm_receiver_filtehbi is
    generic (
        DataWidth : INTEGER := 17;
        AddressRange : INTEGER := 73;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of fm_receiver_filtehbi is
    component fm_receiver_filtehbi_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    fm_receiver_filtehbi_rom_U :  component fm_receiver_filtehbi_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


