// This file is generated by a Matlab script.
// (C) Michael Wurm 2021
// *** DO NOT MODIFY ***

#ifndef _FM_GLOBAL_SPEC_H
#define _FM_GLOBAL_SPEC_H

// Global constants for FM Receiver IP and testbench

// General
#define FP_WIDTH      ((uint32_t)16 + 1)
#define FP_WIDTH_FRAC ((uint32_t)14 + 1)
#define FP_WIDTH_INT  (FP_WIDTH - FP_WIDTH_FRAC)

#define FS            ((uint32_t)960000)
#define FS_RX         ((uint32_t)120000)
#define FS_AUDIO      ((uint32_t)40000)

#define OSR_RX        ((uint32_t)8)
#define OSR_AUDIO     ((uint32_t)3)

// IP specific
#define PILOT_SCALE_FACTOR (6)
#define CARRIER_38K_OFFSET (0.75)

#endif /* _FM_GLOBAL_SPEC_H */
