#-------------------------------------------------------------------------------
# File        : hls_cosim_open_wave.tcl
# Author      : Michael Wurm <wurm.michael95@gmail.com>
# Description : Open waveform that was generated by Vivado HLS co-simulation.
#-------------------------------------------------------------------------------

puts "###############################################################"
puts " Opening waveform"
puts "###############################################################"

set wdb_file "fm_receiver_hls.wdb"
set wcfg_file "fm_receiver_hls.wcfg"

current_fileset
open_wave_database $wdb_file
#open_wave_config $wcfg_file
