-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity channel_decoder_fdEe_rom is 
    generic(
             DWIDTH     : integer := 16; 
             AWIDTH     : integer := 7; 
             MEM_SIZE    : integer := 73
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of channel_decoder_fdEe_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "0000000000000000", 1 => "1111111111101011", 2 => "1111111111101110", 
    3 => "0000000000000101", 4 => "0000000000100110", 5 => "0000000000101101", 
    6 => "1111111111111111", 7 => "1111111110111000", 8 => "1111111110100010", 
    9 => "1111111111101101", 10 => "0000000001101100", 11 => "0000000010100101", 
    12 => "0000000000111100", 13 => "1111111101110000", 14 => "1111111011111101", 
    15 => "1111111101111011", 16 => "0000000010100100", 17 => "0000000101101101", 
    18 => "0000000011101101", 19 => "1111111101100000", 20 => "1111111000100110", 
    21 => "1111111010001101", 22 => "0000000001110101", 23 => "0000001000110100", 
    24 => "0000001000001000", 25 => "1111111111011011", 26 => "1111110110010010", 
    27 => "1111110101100001", 28 => "1111111110101110", 29 => "0000001001111000", 
    30 => "0000001100011110", 31 => "0000000011011110", 32 => "1111110110110010", 
    33 => "1111110010001011", 34 => "1111111010001111", 35 => "0000000111110001", 
    36 => "0000001110010010", 37 => "0000000111110001", 38 => "1111111010001111", 
    39 => "1111110010001011", 40 => "1111110110110010", 41 => "0000000011011110", 
    42 => "0000001100011110", 43 => "0000001001111000", 44 => "1111111110101110", 
    45 => "1111110101100001", 46 => "1111110110010010", 47 => "1111111111011011", 
    48 => "0000001000001000", 49 => "0000001000110100", 50 => "0000000001110101", 
    51 => "1111111010001101", 52 => "1111111000100110", 53 => "1111111101100000", 
    54 => "0000000011101101", 55 => "0000000101101101", 56 => "0000000010100100", 
    57 => "1111111101111011", 58 => "1111111011111101", 59 => "1111111101110000", 
    60 => "0000000000111100", 61 => "0000000010100101", 62 => "0000000001101100", 
    63 => "1111111111101101", 64 => "1111111110100010", 65 => "1111111110111000", 
    66 => "1111111111111111", 67 => "0000000000101101", 68 => "0000000000100110", 
    69 => "0000000000000101", 70 => "1111111111101110", 71 => "1111111111101011", 
    72 => "0000000000000000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "block_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "block";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity channel_decoder_fdEe is
    generic (
        DataWidth : INTEGER := 16;
        AddressRange : INTEGER := 73;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of channel_decoder_fdEe is
    component channel_decoder_fdEe_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    channel_decoder_fdEe_rom_U :  component channel_decoder_fdEe_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


