-- ==============================================================
-- File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ==============================================================

library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fm_receiver_filtedEe_rom is 
    generic(
             DWIDTH     : integer := 17; 
             AWIDTH     : integer := 7; 
             MEM_SIZE    : integer := 73
    ); 
    port (
          addr0      : in std_logic_vector(AWIDTH-1 downto 0); 
          ce0       : in std_logic; 
          q0         : out std_logic_vector(DWIDTH-1 downto 0);
          clk       : in std_logic
    ); 
end entity; 


architecture rtl of fm_receiver_filtedEe_rom is 

signal addr0_tmp : std_logic_vector(AWIDTH-1 downto 0); 
type mem_array is array (0 to MEM_SIZE-1) of std_logic_vector (DWIDTH-1 downto 0); 
signal mem : mem_array := (
    0 => "00000000000000000", 1 => "11111111111010110", 
    2 => "11111111111011100", 3 => "00000000000001010", 
    4 => "00000000001001100", 5 => "00000000001011010", 
    6 => "11111111111111110", 7 => "11111111101110000", 
    8 => "11111111101000100", 9 => "11111111111011010", 
    10 => "00000000011011000", 11 => "00000000101001010", 
    12 => "00000000001111000", 13 => "11111111011100000", 
    14 => "11111110111111010", 15 => "11111111011110110", 
    16 => "00000000101001000", 17 => "00000001011011010", 
    18 => "00000000111011010", 19 => "11111111011000000", 
    20 => "11111110001001100", 21 => "11111110100011010", 
    22 => "00000000011101010", 23 => "00000010001101000", 
    24 => "00000010000010000", 25 => "11111111110110110", 
    26 => "11111101100100100", 27 => "11111101011000010", 
    28 => "11111111101011100", 29 => "00000010011110000", 
    30 => "00000011000111100", 31 => "00000000110111100", 
    32 => "11111101101100100", 33 => "11111100100010110", 
    34 => "11111110100011110", 35 => "00000001111100010", 
    36 => "00000011100100100", 37 => "00000001111100010", 
    38 => "11111110100011110", 39 => "11111100100010110", 
    40 => "11111101101100100", 41 => "00000000110111100", 
    42 => "00000011000111100", 43 => "00000010011110000", 
    44 => "11111111101011100", 45 => "11111101011000010", 
    46 => "11111101100100100", 47 => "11111111110110110", 
    48 => "00000010000010000", 49 => "00000010001101000", 
    50 => "00000000011101010", 51 => "11111110100011010", 
    52 => "11111110001001100", 53 => "11111111011000000", 
    54 => "00000000111011010", 55 => "00000001011011010", 
    56 => "00000000101001000", 57 => "11111111011110110", 
    58 => "11111110111111010", 59 => "11111111011100000", 
    60 => "00000000001111000", 61 => "00000000101001010", 
    62 => "00000000011011000", 63 => "11111111111011010", 
    64 => "11111111101000100", 65 => "11111111101110000", 
    66 => "11111111111111110", 67 => "00000000001011010", 
    68 => "00000000001001100", 69 => "00000000000001010", 
    70 => "11111111111011100", 71 => "11111111111010110", 
    72 => "00000000000000000" );

attribute syn_rom_style : string;
attribute syn_rom_style of mem : signal is "block_rom";
attribute ROM_STYLE : string;
attribute ROM_STYLE of mem : signal is "block";

begin 


memory_access_guard_0: process (addr0) 
begin
      addr0_tmp <= addr0;
--synthesis translate_off
      if (CONV_INTEGER(addr0) > mem_size-1) then
           addr0_tmp <= (others => '0');
      else 
           addr0_tmp <= addr0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
        if (ce0 = '1') then 
            q0 <= mem(CONV_INTEGER(addr0_tmp)); 
        end if;
    end if;
end process;

end rtl;


Library IEEE;
use IEEE.std_logic_1164.all;

entity fm_receiver_filtedEe is
    generic (
        DataWidth : INTEGER := 17;
        AddressRange : INTEGER := 73;
        AddressWidth : INTEGER := 7);
    port (
        reset : IN STD_LOGIC;
        clk : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR(AddressWidth - 1 DOWNTO 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR(DataWidth - 1 DOWNTO 0));
end entity;

architecture arch of fm_receiver_filtedEe is
    component fm_receiver_filtedEe_rom is
        port (
            clk : IN STD_LOGIC;
            addr0 : IN STD_LOGIC_VECTOR;
            ce0 : IN STD_LOGIC;
            q0 : OUT STD_LOGIC_VECTOR);
    end component;



begin
    fm_receiver_filtedEe_rom_U :  component fm_receiver_filtedEe_rom
    port map (
        clk => clk,
        addr0 => address0,
        ce0 => ce0,
        q0 => q0);

end architecture;


