-- This file is generated by a Matlab script.
-- (C) Michael Wurm 2021
-- *** DO NOT MODIFY ***

package fm_global_spec_pkg is

  -- General
  constant fp_width_spec_c      : natural := 16;
  constant fp_width_frac_spec_c : natural := 14;
  constant fp_width_int_spec_c  : natural := 1;
  constant osr_rx_spec_c        : natural := 8;

  -- IP specific
  constant pilot_scale_factor_spec_c : real := 6.00;
  constant carrier_38k_offset_spec_c : real := 0.75;

end package fm_global_spec_pkg;

package body fm_global_spec_pkg is
end package body fm_global_spec_pkg;
